name: alquran_den
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.5
  get: 4.6.3
  lottie: 1.3.0
  flutter_native_splash: 2.2.3+1
  http: ^0.13.4
  google_fonts: 3.0.1
  introduction_slider: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/1.png
  ios: true

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/splash.png

